# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk17

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env:
      global:
        - CODECOV_TOKEN="cc2b8b04-513a-47cd-9c54-369eef30f1fa"

# Отправлять уведомление на почту denis2maximov@gmail.com (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -denis2maximov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always